### ISSUE TITLE
Set up CI for building and uploading pdf

### ISSUE THREAD

**Issue by benediktahrens** [benediktahrens/CT4P#27]
- https://github.com/marketplace/actions/setup-tectonic
- https://github.com/Virtlink/latex-paper-template/

```
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile main.tex
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
      - name: Upload main.pdf
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: build/main.pdf
```
